### ISSUE TITLE
Stylelint linting fails on Windows

### ISSUE THREAD

**Issue by adamazad** [Joystream/joystream-org#222]
`pre-commit` hooks `stylelint` is not working on Windows machine. If you try to commit changes to the repo, you will come across this issue:

![image](https://user-images.githubusercontent.com/1926216/102689345-5cde9b00-420e-11eb-9179-69492fc78821.png)

The solution is to replace 
```
"stylelint": "stylelint 'src/**/*.scss'",
```
with
```
"stylelint": "stylelint src/**/*.scss",
```

in `package.json`

**Comment by DzhideX** [comment]
Thank you for reporting this. The proposed solution would indeed fix the problem on windows but it doesn't work properly on my Linux machine. To make it work on both, the idea is to use escaped double quotes instead of single quotes like this:
```
 "stylelint": "stylelint \"src/**/*.scss\"",
 ```
