### ISSUE TITLE
Role count on network pages

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-org#228]
It generally looks like this on all networks, both past and present.

![Screenshot 2020-12-29 at 14 01 29](https://user-images.githubusercontent.com/437292/103285493-9073af00-49de-11eb-8414-7ecc75b58ca3.png)

Obviously 

1. there should be no counters for a retired network and it should not refer to the current network, as above.
2. an active network should have real counters, it currently does not.

**Comment by blrhc** [comment]
For `1`:
This definitely needs to be fixed, though there are a couple of options for how it should be handled:

We could completely remove the counter element and make it just a button with icon and role name: e.g.
![supportedrolesbasic](https://user-images.githubusercontent.com/4144334/103440848-e2b40a80-4c40-11eb-959d-4151d791fb51.jpeg)

Or we could provide some numbers pertaining to the past testnet:
(e.g. the maximum capacity of the role for that particular release)

![supported roles](https://user-images.githubusercontent.com/4144334/103440871-20b12e80-4c41-11eb-919a-890f7bf0e2c9.jpeg)

@bedeho Let me know which you think would be most appropriate?

And for `2`, this should be a very quick fix, I guess the variable name may have changed on the status server and we overlooked updating it on the actual network pages.

**Comment by bedeho** [comment]
1. Yes lets completely remove.
2. Great.
