### ISSUE TITLE
Broken links to design files

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream-org#249]
The links to design files are broken here: https://www.joystream.org/brand/assets/
and here: https://www.joystream.org/brand/guides/

**Comment by blrhc** [comment]
Thanks for pointing this out, looks like these pages are in serious need of some clean-up work.
Also the repo needs to be updated as soon as possible.

Will make this one of my high priority tasks since some of these assets may be useful to those participating in the Founding Member Program.

**Comment by mochet** [comment]
this is fixed now, so closing
