### ISSUE TITLE
(WIP) List of ongoing website improvements required

### ISSUE THREAD

**Issue by blrhc** [Joystream/joystream-org#262]
### `General`
<img width="193" alt="Screenshot 2021-02-23 at 23 20 13" src="https://user-images.githubusercontent.com/4144334/108921077-b9ef3680-762d-11eb-92cd-682e11a0259f.png">
We need to add a Discord button to the footer
<br>Also Github -> GitHub 

### `/founding-members`
- Back button on the form
- Discord -> Telegram everywhere
- Error message on form if there are endpoint issues
- Suggest ways of making this look better

<img width="506" alt="Screenshot 2021-02-23 at 23 25 57" src="https://user-images.githubusercontent.com/4144334/108922067-8a8cf980-762e-11eb-8308-6e21f061f3e0.png">

### `/manifesto`
The dead link to `joystream.org` needs to be removed here.

![remove dead link](https://user-images.githubusercontent.com/4144334/89885480-08257680-dbc3-11ea-83a3-102d9978791b.jpeg)

### `/athens`

The link to Acropolis should have a different colour (I think white, but maybe underlined?)

![link colour](https://user-images.githubusercontent.com/4144334/89886027-dfea4780-dbc3-11ea-8386-c5355e2de244.jpeg)

### `/sparta`

The contrast is horrible in the warning dialog/text and links, any suggestions? Perhaps all white for the text would be an improvement? And perhaps blue would work better in the background.

And I think again remove the `Network Statistics` part and use the end stats for the network in the `Roles available on the Sparta testnet` section aka. `Incentivized Roles for the Sparta Network`

![sparta text colour](https://user-images.githubusercontent.com/4144334/89886441-89313d80-dbc4-11ea-9302-16862fe3e4d7.jpeg)

Also for both `/sparta` and `/athens`:
This component is broken (showing incorrect data) and I think should be removed, since I'm not sure where the real data is held (not sure if it was ever actually recorded).

<img width="1366" alt="Screenshot 2021-02-23 at 23 16 20" src="https://user-images.githubusercontent.com/4144334/108920889-60870780-762d-11eb-8583-e13e85f0f3e2.png">

One other thing, am I imagining it or on `/sparta` vs. `/athens` is the helment too far down the page and also moves much more noticeably when you scroll down?

**Comment by DzhideX** [comment]
My two suggestions would be:
- For the bounty cards we could make the gap smaller and this is how it would look like:

![get-started-bounties](https://user-images.githubusercontent.com/26174828/109022342-04b78f80-76bc-11eb-9924-d6e3612a4d34.png)

- For the Network Down `HeroCard` we could change the background color to blue and this is how it would look like:

![networkDownInfo](https://user-images.githubusercontent.com/26174828/109022540-33ce0100-76bc-11eb-8974-d6fe2b167c08.png)

Even though I do agree that visibility could be better, I still think that there's some merit to keeping it red as red signifies danger/something is(went) wrong. I think now with the links changed to white, it looks much better even with a red background color.
