### ISSUE TITLE
FM related issues

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream-org#294]
Instead of adding to #293, I'll just list some more issues that needs to be addressed:

- We skipped "last period highlights" for the initial launch, as it would be empty anyway. Now is a good time to add it.
- The link to the KPI and current testnet stats (/testnet) is currently not very accessible, as the previous links to it has been removed.
  - Propose a natural way for users to find it
  - Read through the info, and make changes to the text where needed
- When we publish the "Announcing Sumer" blog post, we need a new network page for it.
- #290
- @bedeho I still think we should refrain from using the name "Atlas" publicly. I would prefer "Joystream Player" instead.

**Comment by bwhm** [comment]
Also I think we need to get develop a standard for submitting summaries. Simply relying on the example text in the [FM-repo](https://github.com/Joystream/founding-members) leads to frustration on both sides (submitting and grading). I don't think it's ok to have users populate a json template, so we would have to make it a little easier...

@DzhideX 
How hard would it be to give users an interactive way of doing this part as well? It would mean that they choose a tasks from a dropdown/list, and depending on the task, they are given fields to populate, with some validation. It would be at least 7 different choices, with some helpers for each. I'll add some examples during the week.

**Comment by DzhideX** [comment]
Sorry for the delay!

I definitely think it would add to the complexity of the whole thing but it shouldn't necessarily be **too** difficult. I think it would also depend a lot on the complexity of the tasks themselves. It may also bring the need to have the designer go through it in case it would deviate from what we currently have in the form.

In any case, examples would help!
