### ISSUE TITLE
Testnet links missing

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-org#302]
It should be possible to click and open the network page for each visible testnet under the `Road to mainnet` section on the landing page, currently it is not.

**Comment by DzhideX** [comment]
I am not quite sure what is meant by this. Currently, whether you click on the cards or either of the scroll buttons (when possible) it will move the card to that Testnet. From there you can click the "Explore `Testnet`" button to go to that particular Testnet. All of the links seem to work as well.

More info would be appreciated!

**Comment by bedeho** [comment]
Ah I see, I did not even see the explore link, I guess I am asking for the image to also become clickable then.
