### ISSUE TITLE
Broken hamburger icon on mobile

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream-org#308]
<img width="430" alt="Screenshot 2021-03-30 at 10 25 22" src="https://user-images.githubusercontent.com/12646744/113133368-daf40a00-921f-11eb-8e2f-5387877f1ad7.png">

Once the menu gets expanded on mobile, the hamburger icon to close the menu is not visible anymore. As an enhancement, we could probably also use some transition there, I can recommend https://github.com/jonsuh/hamburgers for ready to use buttons

**Comment by kosorz** [comment]
I just tried to commit a solution to this bug however I lack relevant permissions.

Here's the working solution:
https://www.awesomescreenshot.com/video/3262517

Here's the code:
![image](https://user-images.githubusercontent.com/32495390/113475235-8e553c80-9474-11eb-8316-0daea3c79a13.png)
![image](https://user-images.githubusercontent.com/32495390/113475239-99a86800-9474-11eb-9234-08f15ada190a.png)

**Comment by blrhc** [comment]
@DzhideX perhaps you can review this solution when you get a chance?

**Comment by blrhc** [comment]
@kosorz Really appreciate this, perhaps you could create a PR to make it easier to review and merge?

**Comment by kosorz** [comment]
> @kosorz Really appreciate this, perhaps you could create a PR to make it easier to review and merge?

![image](https://user-images.githubusercontent.com/32495390/113475909-4cc69080-9478-11eb-93db-098a9d4bc0b0.png)

I tried but I lack relevant permissions.

**Comment by kdembler** [comment]
@kosorz Awesome you got a fix. We work in a forking model - only Jsgenesis team members have write access to the repo. However, you still can open a PR. You will need to fork a repo, push the changes to your fork and then open a PR from your fork to the upstream repo. You should find more details here: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork
