### ISSUE TITLE
Improving the table https://www.joystream.org/founding-members/leaderboards/

### ISSUE THREAD

**Issue by andybut** [Joystream/joystream-org#327]
Hi, guys.
It would be great if you could suggest improving the table https://www.joystream.org/founding-members/leaderboards/.
For example, add for what period the results are displayed. Because it is not entirely clear to users. Or even make a table with the results for each period, which would be even better.

**Comment by bedeho** [comment]
Thank you for the feedback. This is only a leaderboard, so it is only trying to show the most up to date information, not history. You are however right that its not clear to a user whether the leaderboard reflects the most recent scoring period, so it could be useful to have some sort of indicator about how recent the board was updated.
