### ISSUE TITLE
Bug: broken link to whitepaper on blog page

### ISSUE THREAD

**Issue by CrNeppos** [Joystream/joystream-org#348]
There is a broken link on https://blog.joystream.org/ If you click Whitepaper link at the top of the screen, then you'll get 404 page instead of access to Whitepaper file. 

<img width="1552" alt="Screenshot 2021-05-29 at 18 37 25" src="https://user-images.githubusercontent.com/63144564/120076223-23f3fd80-c0ad-11eb-9c16-cc921e93b8c5.png">
<img width="1552" alt="Screenshot 2021-05-29 at 18 38 16" src="https://user-images.githubusercontent.com/63144564/120076228-28201b00-c0ad-11eb-9d59-2609f5702d0c.png">

**Comment by traumschule** [comment]
@CrNeppos Thanks for reporting! This has been fixed and can be closed.
