### ISSUE TITLE
Bug: Next button doesn't work

### ISSUE THREAD

**Issue by CrNeppos** [Joystream/joystream-org#349]
There is a dead button on a submit activity page (https://www.joystream.org/founding-members/form). When Membership handle is typed and Next button is clicked, nothing happens. 

https://user-images.githubusercontent.com/63144564/120077888-5efa2f00-c0b5-11eb-9cb4-febacc146412.mp4

**Comment by blrhc** [comment]
Hey,

Thanks for finding this, we'll investigate and deploy a fix as soon as possible!

**Comment by DzhideX** [comment]
Should be fixed now!
