### ISSUE TITLE
Monero as one of the ways to be rewarded on Joystream

### ISSUE THREAD

**Issue by singulart** [Joystream/joystream-org#372]
Monero cryptocurrency is mentioned many times in multiple site sections as a way to receive rewards for contributing into Joystream ecosystem. This outdated information may confuses users and must be fixed the sooner, the better. 
https://github.com/Joystream/joystream-org/search?q=monero

While working on the Russian translation, I will put up-to-date information (BCH) and not mention Monero at all.

**Comment by blrhc** [comment]
Hey, 

I'm quite confident Monero is mentioned anywhere on the live site, unless you perhaps can provide a screenshot or link?

Thanks nonetheless!

**Comment by singulart** [comment]
https://www.joystream.org/rome/

**Comment by singulart** [comment]
It appears that there's only one link from the live website, so not much to worry about. The rest IMO are from the historical blog posts.

**Comment by singulart** [comment]
No one cares, closing...
