### ISSUE TITLE
Cannot download Joystream Assets from joystream.org: broken Github links

### ISSUE THREAD

**Issue by singulart** [Joystream/joystream-org#375]
When I navigate here: https://www.joystream.org/brand/assets/ and try any of the download links, 404 error is shown. Full list of broken links:

1. https://raw.githubusercontent.com/Joystream/design/master/Assets-full/ZIPPED%20files/Logo.zip
2. https://raw.githubusercontent.com/Joystream/design/master/Assets-full/ZIPPED%20files/Logo%20Icon.zip
3. https://raw.githubusercontent.com/Joystream/design/master/Assets-full/ZIPPED%20files/Descriptive%20Icons.zip 
4. https://raw.githubusercontent.com/Joystream/design/master/Assets-full/ZIPPED%20files/Illustrations.zip
5. https://raw.githubusercontent.com/Joystream/design/master/Assets-full/ZIPPED%20files/System%20Icons.zip
6. https://raw.githubusercontent.com/Joystream/design/master/Assets-full/ZIPPED%20files/Blog%20Covers.zip

**Comment by DzhideX** [comment]
Thank you for finding this information. It should be fixed now!
