### ISSUE TITLE
Bug: Metrics Hero Panel

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/joystream-org#407]
Context: carousel with TestNet metrics on joystream.org is cut off

AR: carousel is not adjusting for responsive dimensions and not scrollable on mobile
ER: carousel is re-adjusting to vertically positioned blocks on mobile devices (⚠️  tbc with design team)

Browser: Chrome, Safari
Device: Chrome sim, but also tested on iPhone 13

Screenshot is in the comments

**Comment by dmtrjsg** [comment]
<img width="828" alt="JoystreamOrg_Testnet_Metrics_Carousel" src="https://user-images.githubusercontent.com/93924525/142005186-6ccee466-2e18-4607-961f-1b49d5b6f605.png">

**Comment by DzhideX** [comment]
This is actually intentional. I remember I did initially make it scrollable but Bedeho was of the opinion (https://github.com/Joystream/joystream-org/pull/270#pullrequestreview-607734123) that it didn't quite look right:
> there should not be a scroller, it looks quite bad, so either have the cards flow, or just clip.

**Comment by bedeho** [comment]
Yes, I rememebr this, I guess the issue there was that the native horisontal scrollbar UI was horrendous, but this can be solved wiith some design input.
