### ISSUE TITLE
New Tokenomics Page

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-org#411]
# Background

The current tokenomcs page in Pioneer, found here

https://testnet.joystream.org/#/tokenomics

Looking like
![Screenshot 2021-11-19 at 14 16 08](https://user-images.githubusercontent.com/437292/142628933-16f5ee05-ad02-4164-9674-3a0ed1d40904.png)

Will no longer be part of Pioneer for Olympia, as Pioneer v2 is totally different, and lots of this information is very specific to testnet initiatives organised by Jsgenesis, while Pioneer will, going forward, only focus on stuff that is part of the Joystream network as of mainnet. For this reason, we will need to find other ways to achieve the goal of this page.

# Proposal

As a starting point, we need to at least try to map out what exact purpose this page is serving right now, before we figure out what to do next. So it would be great if people could provide as much insight on the _problem_ this page is currently solving. **Please focus only on this, and not on possible alternative solutions.**

**Comment by mochet** [comment]
## Purposes
* Users use this page
	* to access the exchange rate frequently. This is the most pivotal piece of information that the page provides (which also impacts what everything else on the page says). This information can't really be shown using chain-state or anything else.
	* to see the current total issuance (otherwise a chain-state query is required)
	* to see fiat pool/replenishment information
	* to understand the number of workers in each group and working group payment info
	* to understand the "current" budget. This is especially useful for developing budgets and other stuff.
		* Specifically, showing the JOY/Week + USD/Week is vital--if this information isn't included, one has to go to the working groups page and perform complex calculations which can only be achieved in a spreadsheet and rely on what the current exchange rate is. This is both time consuming and requires manual updating in line with any payment adjustments or exchange rate changes.
	* to see what the projected token inflation rate is going to be (it is very commonly referred to)
	* to understand stake allocations on the platform (currently, the WGs do not use a realistic amount of stake, but that will change eventually)
	* to understand how much validators are rewarded (there are differing sources for this information, and they are not all the same) which is highly important to understand whether that role is currently profitable or not.
		* it also allows much quicker access to the current validator/nominator count
	* to see peculiarities:
		* for example, I have used this page in the past to notice this: https://github.com/Joystream/joystream/issues/2426
		* it has also resulted in issues like these: https://github.com/Joystream/joystream/issues/2601 (by noticing that the payments are under what they should be)

(the only thing the page does not currently cover is KPIs, which is unfortunate)

**Comment by traumschule** [comment]
As discussed [here](https://discord.com/channels/811216481340751934/815192060276506664/912992443211853895):
https://joystreamstats.live/tokenomics

[Footer link](https://github.com/Joystream/joystream-org/pull/416)

**Comment by bedeho** [comment]
Nice job ;)
