### ISSUE TITLE
mutable numbers in locales

### ISSUE THREAD

**Issue by hitchhooker** [Joystream/joystream-org#422]
locales/en/about.json
```
about:  
  positions:  
   35      "available": "3 jobs available",
```
locales seem to be mentioning how many jobs there is available instead of code calculating how many roles there is in about.json

**Comment by DzhideX** [comment]
I think the idea is that we aren't really looking for new people with all of those roles necessarily. This also hasn't really changed in a long time and hard-coding the value was the easiest way to do it. If it does change in the future though, I'll make sure to make the value dynamic if it makes sense. Thanks for the suggestion :+1:
