### ISSUE TITLE
Onboarding Front End Development

### ISSUE THREAD

**Issue by mrexpat** [Joystream/joystream-org#433]
Task breakdown TBD

**Comment by traumschule** [comment]
Implementation goes smoothly, On Jan 31th we agreed to finish within 2 weeks.

Current status as per #442
- [X] Page 1: [what is joystream](https://joystream-org-git-fork-oleksanderkorn-onboarding-ui-joystream.vercel.app/start-here/what-is-joystream)
- [X] Page 2: [joystream as dao](https://joystream-org-git-fork-oleksanderkorn-onboarding-ui-joystream.vercel.app/start-here/joystream-as-dao/)
- [X] Page 3:  [fm program](https://joystream-org-git-fork-oleksanderkorn-onboarding-ui-joystream.vercel.app/start-here/what-is-fm-program)
- [X] Page 4: [council](https://joystream-org-git-fork-oleksanderkorn-onboarding-ui-joystream.vercel.app/start-here/what-is-council)
- [X] Page 5: [working groups](https://joystream-org-git-fork-oleksanderkorn-onboarding-ui-joystream.vercel.app/start-here/what-are-working-groups)
- [X] Page 6: [bounties](https://joystream-org-git-fork-oleksanderkorn-onboarding-ui-joystream.vercel.app/start-here/what-are-bounties)
- [X] Role: [video creator](https://joystream-org-git-fork-oleksanderkorn-onboarding-ui-joystream.vercel.app/start-here/video-creator/)
- [ ] other roles, lessons, navigation between videos/pages

Details
- bounties are loaded from GH as before
- FAQ  reuses the TokenInformation component
- avatars come from https://api.joystreamstats.live/api/v1/members
- workers are fetched live (client side) from chain by iterating over reward relationships

*last update: Feb 4th*

**Comment by oleksanderkorn** [comment]
Contributor pages:

- [ ] [Builder](https://joystream-org-git-fork-oleksanderkorn-onboarding-ui-joystream.vercel.app/contribute/builder)
- [ ] [Techie](https://joystream-org-git-fork-oleksanderkorn-onboarding-ui-joystream.vercel.app/contribute/techie)
- [ ] [Organiser](https://joystream-org-git-fork-oleksanderkorn-onboarding-ui-joystream.vercel.app/contribute/organiser)
- [ ] [Curator](https://joystream-org-git-fork-oleksanderkorn-onboarding-ui-joystream.vercel.app/contribute/curator)
- [ ] [Marketer](https://joystream-org-git-fork-oleksanderkorn-onboarding-ui-joystream.vercel.app/contribute/marketer)
- [ ] [Video Creator](https://joystream-org-git-fork-oleksanderkorn-onboarding-ui-joystream.vercel.app/contribute/video-creator)

**Comment by traumschule** [comment]
looks complete: https://github.com/Joystream/joystream-org/pull/442
