### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by traumschule** [Joystream/joystream-org#438]
The banner informs about use of Cookies but not Tracking (#53).

Since Joystream is not a household activity it needs to be [upfront](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation#Transparency_and_modalities) about it:

> This website uses external trackers from ...

- [ ] Find locations that include external trackers
  - `src/data/siteMetadata.js` adds `cdn.livesession.io/track.js`.

**Comment by DzhideX** [comment]
Thank you for bringing this to our attention. Should be fixed now :+1:

**Comment by traumschule** [comment]
The banner automatically disappears after some milliseconds maybe because i already have an livesession ’account’? Then i will never know that the guideline has changed because the privacy policy is not linked on the homepage.

**Comment by DzhideX** [comment]
It is because you've already accepted the cookie notice before and the cookie itself lives for a long time (365 days). Do you think it'd be necessary to reset the cookie for all users now that the policy has been changed?

**Comment by traumschule** [comment]
I believe so.

https://gdpr.eu/cookies/
> To comply with the regulations governing cookies under the GDPR and the ePrivacy Directive you must:
> Receive users’ consent before you use any cookies except strictly necessary cookies.
> Provide accurate and specific information about the data each cookie tracks and its purpose in plain language before consent is received.
> Document and store consent received from users.
> Allow users to access your service even if they refuse to allow the use of certain cookies
> Make it as easy for users to withdraw their consent as it was for them to give their consent in the first place.

https://termly.io/resources/articles/gdpr-cookies/#gdpr-compliant-cookie-consent
> This consent relies on two fundamental components:
> Users’ awareness of your cookie use (including cookie categories and purposes)
> Users’ ability to consent to, deny, or set preferences for your use of cookies
