### ISSUE TITLE
Suggested change for front page (Change "Product" wording)

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream-org#441]
I don't know if any other changes already have something like this planned:
- Rename or change `Product` to indicate or say `Testnet`. **`Testnet`** or **`Launch app`** are the most commonly used terms on DAO/crypto websites. It could even say `Incentivized Testnet`
- The footer of the website should also ideally say "TESTNET" in some big way.

**Comment by bedeho** [comment]
Agree.

**Comment by DzhideX** [comment]
I believe this is not relevant anymore so I will be closing it.
