### ISSUE TITLE
Drop stuff

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-org#482]
Drop following sections on main page

1. Manifest
2. FM
3. Why join our testnets?
4. `Earn mainnet tokens, cash and influence.`

- Drop roles page

**Comment by mrexpat** [comment]
I might just rethink the whole main page with a more holistic approach.. just adding and removing stuff like we are now might end up with a frankenstein type of page..

How about I propose something tomorrow?

**Comment by bedeho** [comment]
Well I agree with the basic premise, but a full page redesign is a big project, it arguably requires a will site redesign, and that has to be informed by some more long term strategic shift, which I think its a bit too early to pin down. I'm open to reviewing anything, perhaps there is some middleground there, just warning that this fix was ok to me precisely because it was a 0 effort, 15s type of improvement, not a big project.

**Comment by mrexpat** [comment]
Sure thing

**Comment by mrexpat** [comment]
> Drop following sections on main page
> 
> 1. Manifest

Drop

> 2. FM

Wouldn't mind keeping this, as it provides a little more info. Possibly link it to the onboarding though.

> 3. Why join our testnets?

Drop

> 4. `Earn mainnet tokens, cash and influence.`

I'd keep this.

> * Drop roles page

Why do you want to drop this? Is it not relevant anymore?

**Comment by bedeho** [comment]
> Why do you want to drop this? Is it not relevant anymore?

Correct, its actually misinformation at this point.

> Earn mainnet tokens, cash and influence.

Why?  

>  Wouldn't mind keeping this, as it provides a little more info. Possibly link it to the onboarding though.

Ok.

**Comment by mrexpat** [comment]
> > Earn mainnet tokens, cash and influence.
> 
> Why?

Acts as a final CTA for onboarding for the bottom of the page.. as people scroll down the page to see if there's something else interesting chances are they reach this section and realize "this is the most interesting thing here... CLICK"

**Comment by bedeho** [comment]
> Acts as a final CTA for onboarding for the bottom of the page.. as people scroll down the page to see if there's something else interesting chances are they reach this section and realize "this is the most interesting thing here... CLICK"

We already have so many points of entry for that.

**Comment by mrexpat** [comment]
> > Acts as a final CTA for onboarding for the bottom of the page.. as people scroll down the page to see if there's something else interesting chances are they reach this section and realize "this is the most interesting thing here... CLICK"
> 
> We already have so many points of entry for that.

Off it goes!

I'll get Edvin on it

**Comment by mrexpat** [comment]
@DzhideX Pls remove on the home page

Manifesto section
Why join our testnets? section
Earn mainnet tokens, cash and influence. section

Also kill the Roles page, and the footer link to it. Let me know when done pls :)

**Comment by mrexpat** [comment]
While at it.. @DzhideX pls change this also

**Comment by DzhideX** [comment]
We can't do that as we don't have the Olympia page ready yet. @blrhc Do you have the necessary data for me for that? I would be able to finish it up on the weekend now..
