### ISSUE TITLE
Design Brief: Surface attractiveness of participation

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-org#484]
# Background

Right now, it is possible for people to participate in a very wide range of activities on the testnets. A concrete list can be found here

https://joystream.gitbook.io/testnet-workspace/#opportunities

There are in fact 16 activities available. At any given time, the people are earning both cash ($tJOY) and mainnet tokens ($JOY), which in total are worth a great deal. How much you are earning varies from activity to activity, and also from week to week.

This spreadsheet gives a model which tries to give some example values of what people can be earning for different activites

https://docs.google.com/spreadsheets/d/1j-YGq6NyqwCmA2wMdKNHMqicosUXzDFEx6lrxhvwaFI/edit#gid=0

# Problem

Because of the number of activities, and the change from week to week, there is no easy way for people to discover and stay on top of this information. This is negatively impacting participation in the testnet, and growth and acquisition of prospective high value contributors and eventual Founding Members

# Proposal

Add two sections to our main website

1. A section which shows what the different activities are, including a name and perhaps a one liner, and emphasising the total weekly compensation. Also fine with clickable link that sends you straight to integrators.
2. A section (perhaps combined with the existing Founding Member Program section) which shows how much value has already been earned by lets say the top 5 people the last 3 council periods, where we really highlight their 
   - avatar
   - handle
   - activities
   - USD value of $JOY unlocked
Also we should list how much USD value in $JOY you should have to earn in order to become a founding member, this number is dynamic and is fetched from a server which can be slow.

**Comment by mrexpat** [comment]
Nothing really to add here.. all for this

**Comment by singulart** [comment]
Or else, have the HR/Marketing Squads socialize this in all possible channels.

**Comment by mochet** [comment]
The current design doesn't show the current number of `participants` (which is 47, ranged across several different activates and doesn't include validators).

Showing that each `activity` has some number of participants is likely a key driver of interest/activity.

**Comment by MattAugustynowicz** [comment]
[👉 Figma link here](https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=4869%3A288266)

1️⃣ Different Activities
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/95480823/164725336-56f65e87-bfcf-49c9-aa70-4fd99cd5cf71.png">

2️⃣ FM Program Section
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/95480823/164725450-5780e2e4-c6cf-4680-9f52-494b247a7b0e.png">

**Comment by traumschule** [comment]
Please update https://www.joystream.org/token (`Understanding the tJOY token`)
This is still the best we have https://joystream.gitbook.io/testnet-workspace/usdjoy
