### ISSUE TITLE
Problem: onboarding section bounty page shows bounties that are not active

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream-org#500]
https://www.joystream.org/start-here/what-are-bounties

SSIA

**Comment by traumschule** [comment]
[Hid them](https://github.com/Joystream/community-repo/commit/77cc1ad047d3460bbefca4c4cbc9a402b30975b9), now the page looks weirdly empty. Should get bounties from QN.

**Comment by DzhideX** [comment]
Indeed, the onboarding section was created during Giza and I haven't really had the time to update it since then. I'll take a look at this and all of the other pages as well. Thanks for reporting this :100:
