### ISSUE TITLE
Persistient responsiveness issues.

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-org#52]
I believe I gave a review a while back about fixing many of these issues, for some reason they were not. In summary, the site breaks or has a bad design, as it is being scaled.

All of these are issues currently on the `master` branch, I will not proceed to review any open PRs until these are resolved or responded to, and the new PRs are rebased on/merge fixes.

1. This is not how the design shows these being rendered, the design showed the label and information on the right-hand side.
<img width="284" alt="Screenshot 2019-11-06 at 09 04 47" src="https://user-images.githubusercontent.com/437292/68280283-83c32780-0075-11ea-92da-3ee92a1e7fda.png">.

2. Can we change to use this illustration

https://projects.invisionapp.com/share/7DQGW3738SX#/screens/383369696

3. When resizing, many illustrations are scaled-down and shifted, this looks broken.

Just hide it if there is no space.

<img width="975" alt="Screenshot 2019-11-06 at 09 10 37" src="https://user-images.githubusercontent.com/437292/68281771-a440b100-0078-11ea-9920-f2873267d4e2.png">

![Screenshot 2019-11-06 at 09 35 56](https://user-images.githubusercontent.com/437292/68281905-ea961000-0078-11ea-9af4-98aaeda601ba.png)

4. These buttons take the full width of the screen too early.

<img width="985" alt="Screenshot 2019-11-06 at 09 43 38" src="https://user-images.githubusercontent.com/437292/68282452-0a7a0380-007a-11ea-96e5-51fcc62d9ddd.png">

5. The top-level menu wraps and breaks.

<img width="1026" alt="Screenshot 2019-11-06 at 09 05 39" src="https://user-images.githubusercontent.com/437292/68281812-bc183500-0078-11ea-9f62-25445e2d5143.png">

6. The status card, which has title "NETWORK ANNOUNCED", is its font scaled down even as the horizontal space is _increased_ because the right hand side illustration is removed. This should not happen. See the next three images.

<img width="532" alt="Screenshot 2019-11-06 at 09 49 25" src="https://user-images.githubusercontent.com/437292/68282899-cd624100-007a-11ea-8861-88c6ad4a3d8f.png">

<img width="598" alt="Screenshot 2019-11-06 at 09 49 32" src="https://user-images.githubusercontent.com/437292/68282902-cfc49b00-007a-11ea-86dd-ae06768694ab.png">

<img width="582" alt="Screenshot 2019-11-06 at 09 49 37" src="https://user-images.githubusercontent.com/437292/68282917-d3f0b880-007a-11ea-8a1b-aa5749c665ed.png">

7. Avoid this bad title wrap.

<img width="317" alt="Screenshot 2019-11-06 at 09 51 21" src="https://user-images.githubusercontent.com/437292/68283019-07cbde00-007b-11ea-8bfd-e6c9d8b6ab3b.png">

8. The network page breaks when resized. The title is too small and the  "What is this" just floats in mid air despite there being no network logo available to ask the question about

<img width="917" alt="Screenshot 2019-11-06 at 09 10 52" src="https://user-images.githubusercontent.com/437292/68282188-7c9e1880-0079-11ea-94b2-e601f734b5bf.png">

9. The roles headers break.

<img width="618" alt="Screenshot 2019-11-06 at 09 52 47" src="https://user-images.githubusercontent.com/437292/68283173-5ed1b300-007b-11ea-9065-175c5b3ea0ce.png">

<img width="629" alt="Screenshot 2019-11-06 at 09 52 59" src="https://user-images.githubusercontent.com/437292/68283174-5ed1b300-007b-11ea-815a-7c61930e06f3.png">

<img width="622" alt="Screenshot 2019-11-06 at 09 53 03" src="https://user-images.githubusercontent.com/437292/68283175-5ed1b300-007b-11ea-8e03-d0130824277c.png">

**Comment by blrhc** [comment]
@maciejmatu, could you fix this in your open PRs?

**Comment by maciejmatu** [comment]
Sure thing. Some of the issues are already addressed in the open PR-s, e.g. Navigation responsiveness issue. I can add fixes for them on #51 PR if that's okay with you, @bedeho. Since I can't push to master/development I have to do it through a PR anyways

**Comment by blrhc** [comment]
@maciejmatu That would be fine. Let me know when you have everything mentioned above sorted and I will review again.

**Comment by maciejmatu** [comment]
@bedeho regarding the first issue, do you want me to keep only 6 of the tiles as on the design? Currently we how 8 of them, whereas on the design there are six. 

![image](https://user-images.githubusercontent.com/10004167/68382459-028e9200-0154-11ea-9422-47b826234fcc.png)

**Comment by bedeho** [comment]
No lets keep the eight. When you fix this, can you have two separate components, so that we have the benefit of the work you have already done. We can then pick one or the other depending on how it looks when we change the content

**Comment by maciejmatu** [comment]
Sure, I will split it into two separate components 👍
