### ISSUE TITLE
Analytics for joystream.org and pioneer

### ISSUE THREAD

**Issue by blrhc** [Joystream/joystream-org#53]
### Introduction
We currently have Google Analytics enabled for both [joystream.org](https://joystream.org) and [Pioneer](https://testnet.joystream.org/acropolis/pioneer/#/). Unfortunately, it isn't offering us very much useful information about how people are using either of these services. We have therefore decided to switch to Mixpanel for the reasons outlined below.

### Mixpanel vs Google Analytics
While Google Analytics is a good general purpose solution for tracking what kind of visitors a service gets, it is relatively weak at offering insights into what they do once on the website or application. Mixpanel is arguably much more event-driven, and this is what we really need in order to understand how users are behaving on our testnets.

![ga](https://user-images.githubusercontent.com/4144334/68431485-414f3700-01aa-11ea-9af4-2f7e9877555d.jpeg)

Google Analytics is intended more for static websites as opposed to applications such as Pioneer.  It provides useful demographic information, but its systems for tracking events are quite clumsy and the data is often poorly represented. 

With Mixpanel, it appears to me that it will be very simple to track actions such as video plays, button clicks and elements viewed. The diagrams etc. which result from placing a simple snippet of Javascript e.g. `mixpanel.track("Video play");` on each element we want to track will end up being useful for measuring what people do on Pioneer and joystream.org too.

<img width="1325" alt="Screen Shot 2018-12-04 at 2 32 38 PM" src="https://user-images.githubusercontent.com/4144334/68431861-1d402580-01ab-11ea-9d32-be313a1fb2ac.png">

### What we might want to track for Rome
It would be useful at this point to consider what kind of events we would like to track in pioneer. Here are some of the main ones we might like to measure:
- Media plays (segmented by type of media: video, music, podcast, book?)
- Clicking text fields
- Entering "pages"*
- Leaving "pages"*
- Changing memo
- Adding content item
- Changing visibility of content item
- Button clicks
- Etc.

*e.g. upload video form, extrinsics page, testnet data page

I'd appreciate some comments on this issue offering some more examples, perhaps by those who are more familiar with the flows designed for Rome. My general attitude is that we should collect as much data relating to as many distinct events as possible and work out what it will be useful for later. This approach is likely to provide us with a higher proportion of information that we can act on to improve our testnet software.

### Summary
I will attempt to deploy Mixpanel tracking to both the new Joystream website (currently just the development version of that site) and eventually Pioneer, though may need a bit more guidance with the latter. Once live, we will have to remember to update the joystream.org and Pioneer privacy policy to reflect the change in analytics provider.

**Comment by bedeho** [comment]
1. Let's go with Mixpanel.

2. Can you try to narrow down the list of what to measure, and make it more connected with perhaps one or two critical key results?

**Comment by blrhc** [comment]
1. Great!
2. Certainly, will update here.

**Comment by blrhc** [comment]
@bedeho, do you want me to suggest some new analytics-based key results, or are you referring to key results in the sense of the [existing ones](https://github.com/Joystream/joystream/tree/master/okrs#objective-engage-community-to-understand-rome-and-join-us-in-the-future) we have and linking some sub-KRs into those?
