### ISSUE TITLE
Broken typewriter text

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-org#539]
Pretty absurd text that is typed out on http://www.joystream.org/ru, 

![Screenshot 2022-09-13 at 17 59 05](https://user-images.githubusercontent.com/437292/189950060-23852e8f-3186-4c4a-bf3f-e7c602213a47.png)

**Comment by DzhideX** [comment]
There is a [PR](https://github.com/Joystream/joystream-org/pull/538) with the fix for that issue (and other problems) waiting to be merged. Would you mind being the one to review it and merge it as it's been sitting there for a bit?

**Comment by bedeho** [comment]
Great :)
