### ISSUE TITLE
post-launch website improvements

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream-org#544]
(WIP)
A few notes based upon having visited hundreds of different project websites in the past few days:
1. The main "frame" that a user immediately sees should be populated with current chain activity. Any user visiting should immediately see some indication of current chain activity
2. Kill links to the blog etc unless they are actually going to be updated regularly, lots of projects have blogs that haven't been updated in months/years and it is a bad look.
3. Change Discord link to "Community": https://github.com/Joystream/joystream-org/issues/404
4. Link to GitHub more prominently (possible idea: https://deip.world/github)

**Comment by bedeho** [comment]
> The main "frame" that a user immediately sees should be populated with current chain activity. Any user visiting should immediately see some indication of current chain activity

Why? I think you need to start from first principles about what the purpose of the page is: what is it trying to convey to whom.

The current page has a very deliberate thesis, and showing random block heights or membership counts has no direct relevance to it. I invite you to review that plan and see if you think
a) the thesis is wrong
b) the page should still have it despite the hesis

**Comment by mochet** [comment]
> Why? I think you need to start from first principles about what the purpose of the page is: what is it trying to convey to whom.

I wouldn't say my suggestions are for immediate action, just notes based on visiting many projects where activity and things are hidden behind wallet prompts and poor navigation. There often seems to be very little emphasis on activity and some project webpages don't seem to do well in getting people interested or thinking about being proactively involved.

I think because the only indication of activity/opportunity I get as a new user is far down the page with the openings/WG section. Although the current main "frame" is an opportunity it is not a live one, so it could really just be adjusted at some point to show how many people have claimed their channels recently.

I think I'll be continuously revisiting how the page is designed (at least from my own perspective) as time progresses because a great number of project websites have a lot of faults and can end up becoming very stale.

**Comment by bedeho** [comment]
> I think I'll be continuously revisiting how the page is designed (at least from my own perspective) as time progresses because a great number of project websites have a lot of faults and can end up becoming very stale.

Agreed.

>  There often seems to be very little emphasis on activity and some project webpages don't seem to do well in getting people interested or thinking about being proactively involved.

I think we do speak very directly about how people can get involved, but we can't speak about every possible way to get involved with equal emphasis, that will just be ineffective. At any rate, showing activity does not actually seem like the most way to get people involved.

There is going to be more "activity" related information on the page when we go on mainnet, but it will be related to the messaging we are actually focusing on. So it will be in the form of banners in each of the sections that talk about recent payouts to creators, recent NFTs sold, etc., so it's clear that things are actually happening relating to what we are talking about. But just generic contents tuff like blockchain metrics or recent proposals, that stuff will just confuse the primary messaging if it's anywhere prominent.

**Comment by traumschule** [comment]
Left [my ideas](https://github.com/Joystream/atlas/issues/3321#issuecomment-1321173060) in the wrong ticket.
