### ISSUE TITLE
Tweaks to main page

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-org#55]
Please reply to issues in this thread if needed, resolve in standalone PR.

1. Can we somehow lift this illustration further up, it sits very low. It may just be becaue the motif itself occupies frame in a different way to the illustration in the design, but it needs to be accounted for in the layout.

**Stadium illustration**

<img width="1287" alt="Screenshot 2019-11-18 at 11 58 06" src="https://user-images.githubusercontent.com/437292/69047135-c7fde280-09fa-11ea-8025-a71121195098.png">

**Builders illustration**

<img width="1229" alt="Screenshot 2019-11-18 at 11 58 01" src="https://user-images.githubusercontent.com/437292/69047170-d64bfe80-09fa-11ea-802e-1b06bc3e4b0f.png">

2. The illustration for the current testnet, and the pattern in the background is much smaller than in the design, even with maximal space available.

**Design**

<img width="879" alt="Screenshot 2019-11-18 at 11 33 23" src="https://user-images.githubusercontent.com/437292/69046815-2aa2ae80-09fa-11ea-8552-96bae6c9ec4c.png">

**Page**

<img width="872" alt="Screenshot 2019-11-18 at 11 53 38" src="https://user-images.githubusercontent.com/437292/69046828-30988f80-09fa-11ea-9e71-876ca1383b4e.png">

3. The metrics section for the testnet merges with the next "Roles" section because there is no next announced testnet section currently. This is a failure of the design, not of the page. However, we could potentially ameliorate it somewhat by introducing a suitable subtitle for the metric section, which currently is blank.

<img width="1217" alt="Screenshot 2019-11-18 at 11 32 26" src="https://user-images.githubusercontent.com/437292/69046976-72293a80-09fa-11ea-91d4-a2dd4fc3896b.png">

4. The testnte metic icons appear to be smaller than they need to, even with maximal space. Lets have them have their actual size from the design.

**Design**

<img width="1458" alt="Screenshot 2019-11-18 at 11 27 13" src="https://user-images.githubusercontent.com/437292/69046995-7d7c6600-09fa-11ea-85e4-cdabae2536ab.png">

**Page** 

<img width="1300" alt="Screenshot 2019-11-18 at 11 26 30" src="https://user-images.githubusercontent.com/437292/69047000-82411a00-09fa-11ea-9d3a-0d0e32ffaf27.png">

**Comment by blrhc** [comment]
@maciejmatu

**Comment by maciejmatu** [comment]
@bedeho 
4. This is what it would look like with enlarged images. If we break to 3 items per row then I we will be able to make it as big as on the design, but with 4 items, we'll get text-breaking (the biggest problem is the long "Not Running" text, that breaks to a newline). But if what's on the screenshot is fine I will update it this way.
![image](https://user-images.githubusercontent.com/10004167/69063942-a3673200-0a1d-11ea-8e56-0db37096953e.png)

**Comment by bedeho** [comment]
**Regarding issue 3:**
Yes that helps, but actually, could yous till try, because there will be times where there is no new network announced, e.g. in some time window after Rome is deployed.

**Regarding issue 4:**
No wrapping is acceptable, it severly degrades ledgibiilty. I see now in the design this is not dealt with as well as I remember. This should be addressable by simply affording greater horizontal space for the text label container. This means the horizontal space required for each unit will probably increase, and thus the minimum horizontal width at which the container can hold the full 4 units will also increase, but that is not a problem. Also shortening some of the labels could make sense, do you think you could come up with slightly more succinct versions for some of them? e.g. "Active Storage Providers" => "Storage Providers"

**Comment by maciejmatu** [comment]
**Regarding issue 3:**
I added a `title` property, so when needed you can add it. Is this what you had in mind?
![image](https://user-images.githubusercontent.com/10004167/69146009-2c8a7180-0acf-11ea-9dd5-3dd6b37ebd08.png)

**Regarding issue 4:**
I changed the block max-width, and shortened the titles. If needed I can make it even bigger. On the screenshot this is what it looks like on ~1500px with. On the smallest breakpoint the only word that breaks to a newline is `Not Running`
![image](https://user-images.githubusercontent.com/10004167/69148029-aa507c00-0ad3-11ea-94dc-d1d69c6a8278.png)

**Comment by blrhc** [comment]
↑ @bedeho

**Comment by bedeho** [comment]
Yes exactly, seems to work reasonably. Icon size is still same as before though, right?

**Comment by maciejmatu** [comment]
@bedeho I made them ~15% larger. Here is the comparison on `1400px`. Top is before, bottom is after
![image](https://user-images.githubusercontent.com/10004167/69229043-fd363c00-0b84-11ea-8fe7-2315abc9ea38.png)

**Comment by bedeho** [comment]
Great job, thanks for the clear comparison.
