### ISSUE TITLE
Add YPP info to JS.org landing page

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/joystream-org#577]
@dmtrjsg commented on [Thu Aug 04 2022](https://github.com/Joystream/marketing/issues/275)

## Context

It is highly likely that js.org landing page will get done before YPP is launched, meaning we need to first cook a version without any references about the YPP payments, and add the relevant details later.

## Scope

- [ ] Add YPP banner
- [ ] Add "learn more" link to the payments section

**Comment by dmtrjsg** [comment]
@toiletgranny can you pls kindly share the link from Figma to the comments?

**Comment by toiletgranny** [comment]
@dmtrjsg Note that we never finalized this section; for some reason, we dropped it at the hi-fi iterations stage. I put together everything again, using the most recent version of the illustration we were looking at. You might want to review the copy, though, @dmtrjsg.

Meanwhile, @DzhideX:
1. Here's the desktop version of this section: https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=7884%3A409393&t=nuln39pqAIlMKXpy-4
2. Here it is on mobile: https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=7884%3A440911&t=nuln39pqAIlMKXpy-4
3. And here you can export the illustration: https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=7884%3A441037&t=nuln39pqAIlMKXpy-4

**Comment by bedeho** [comment]
When was this planned, I am not sure this is appropriate for the landing page.

YPP is a feature & policy that some apps may or may not chose to run, its not fundamental to the project/blockchain/platform in a way that makes it appropriate on the Joystream project page, there is no canonical _YouTube Partner Program_ to speak of. This would be appropriate to have on the Gleev landing page, when speaking directly to creators who may want to opt into a specific program with specific terms, when its put on the main website
