### ISSUE TITLE
UI bug on NFT cards

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-org#608]
From carousel on front page. Does this imply same bug exists in Atlas? if so, perhaps you could open a PR to fix that also ?

![Screenshot 2023-04-06 at 18 31 20](https://user-images.githubusercontent.com/437292/230440717-3eb9abd2-54fe-460a-9284-0b07292102ab.png)

**Comment by DzhideX** [comment]
I noticed this and immediately pushed out a fix yesterday (it was a bug on the status server, Atlas shouldn't be affected). It could be that this data was potentially cached in the browser, could you confirm that you're still seeing the problem?

On my end it looks like this now:
<img width="292" alt="Screenshot 2023-04-07 at 13 13 00" src="https://user-images.githubusercontent.com/26174828/230599882-33d135a0-ba49-4be9-916f-948c8e1b4c00.png">

**Comment by bedeho** [comment]
> could you confirm that you're still seeing the problem?

No problem now.
