### ISSUE TITLE
Update block explorer links in footer

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-org#625]
Same conclusion as this: https://github.com/Joystream/pioneer/issues/4389#issuecomment-1558581190 , so add two distinct links, but obiovusly without icons.

**Comment by DzhideX** [comment]
The linked comment assumes that we link to [polkadot.js](https://polkadot.js.org/apps/?rpc=wss://rpc.joystream.org:9944#/explorer) similar to how it's done on Pioneer but we actually link to [Polkadot Subscan](https://polkadot.subscan.io/). The question is, next to adding a link to Calamar, do we want to keep the existing link to polkadot.subscan or do we want to change it polkadot.js?

**Comment by bedeho** [comment]
We are not listed on subscan, so its just a mistake to link to it. What I'm saying is that that link should be pointing to Calamar, and then we add a new link that can serve as link to the polkdaot js site.

**Comment by DzhideX** [comment]
Got it!
