### ISSUE TITLE
Add FIAT representation to JOY tokens

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/joystream-org#640]
<img width="628" alt="Screenshot 2023-07-04 at 19 02 59" src="https://github.com/Joystream/joystream-org/assets/93924525/d84453b1-213e-46d7-b9c8-08b47847302f">

**Comment by KubaMikolajczyk** [comment]
Fiat denomination was added to all 3 mentioned component, but this required also to make some other changes to the components except of simply adding the denomination itself.

# Channel payout card
![image](https://github.com/Joystream/joystream-org/assets/31144205/cba7a62b-311d-4197-a6ea-749ea000dabc)
- Reworked the order of text on the card so we can place the Fiat denomination without making the component looking overloaded. 
- Changed the spacing between elements inside the component

📄 Channel payout card: https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?type=design&node-id=5966-275478&mode=design&t=Bfecm1s3sLmNokW3-4

# Video NFT card
Here simply added the fiat denomination
![image](https://github.com/Joystream/joystream-org/assets/31144205/d0927f29-0413-4dd5-9bfe-f1024f6be32a)

📄 Video NFT card: https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?type=design&node-id=5966-275596&mode=design&t=Bfecm1s3sLmNokW3-4

# Opportunity Box 
![image](https://github.com/Joystream/joystream-org/assets/31144205/f9203811-8050-49df-bfdd-d0f4e2b190a4)
- Had to create a component for it from scratch as it was nowhere to be found in designs
- Added denomination, but also changed the way that the price itself is displayed
- Updated all pages using it with the new component

📄 Opportunity box: https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?type=design&node-id=8557-409063&mode=design&t=Bfecm1s3sLmNokW3-4

📄 Homepage desktop : https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?type=design&node-id=6923-383359&mode=design&t=Bfecm1s3sLmNokW3-4
