### ISSUE TITLE
Roadmap on website

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream-org#643]
Making an issue to capture feedback on the roadmap (specifically examples of roadmaps that look nice for inspiration).

I also think that the roadmap should include the pre-launch features that were already developed, there is a table somewhere of all the products that have already been built + developed within the project and this would help to better communicate what features have _already_ shipped and help with the project's reputation.

**Comment by bedeho** [comment]
Look at this:  https://github.com/Joystream/joystream-org/issues/644
