### ISSUE TITLE
Roadmap Page Brief

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-org#644]
# Background

Currently it is hard for to keep track of the objectives of various ecosystem participants are for what to build at what time in the future. This information is distributed among a wide range of formal and informal venues, like chats, forum posts, proposals, live streams and long form video presentations. Getting an up to date and integrated view is at this time difficult.

# Proposal

Introduce a new page on the https://www.joystream.org website, with a place in the top menu, which holds a so-called roadmap view across the project. This new page will present the current most up to date aspirations for what is will be shipped. Importantly, the primary audience of the roadmap is relative newcomers trying to guague where the project is going, hence it should not be interpreted as a detailed and granular issue tracker with lots of minor enhancements with narrow objectives, but rather broad 

# Design Brief

- The design needs variations for mobile, tablet and desktop.
- The design should follow the Joystream brand identity guide: https://www.joystream.org/brand/guides
- The design should follow the composition of other pages, e.g. https://www.joystream.org/community, which likely means that there is a need for at least one new illustration for the hero section.
- There has to be a preamble which sets the context for the roadmap itself, so as to set the expectation in the mind of the reader about what the roadmap actually means. Here it will be pointed out that the roadmap is high-level, and not a guarantee, and that should be expected to change. There likely be a link to external resources that provide further social legitimacy to the proposal.
- The roadmap must have a very clear revision number, which allows unambigious identification of a specific plan, despite the most up to date plan changing possibly frequently. The user should clearly see the revision number, and be able to select a prior version out of some list of other overview of all versions that exist. The easiest format is simply to use natural number versions, so 1,2,3,... and so on. There should be contextual information which explainss what the role of the version number is.
- The roadmap itself will be organized into years (2023, 2024, ..), and within each year into quarters (Q1,...,Q4), and within each quarter ther will be a list of delivery milestones. In practice the roadmap is unlikely to span more than two years into the future. The meaning of milestone is the completion of some meaningful coherent user relevant work, but the work itself may have began a long time ago. The roadmap should only display future milestones.
It in principle would be possible for a quarter to be empty, but not likely, and a quarter will probably max have 5 milestones, probably more like 2-3. Each milestone will have a short high level title, and a longer full text description, which itself may include links.
- There should be a glossary section, which offers definitions of terms or names that are reused heavly across the roadmap, and uses of these terms should allow linking to these glossary entries.
- There should be a reference section, so that granular context can be added to very specific points in the text, outside of the flow of the text.
- There should be a disclaimer section at the bottom.

# Example Roadmap

## 2023

- **Q3**
  - **Content Recommendation V2:** Surfacing personalised content for a consumer is a key requirement for any content platform. Key product experiences like home screens, feeds and related content, all depend on having modern machine learning based content recommendation system. Currently Orion has no infrastructure to produce or serve such recommendations, and app recommendations are being done entirely client-side. The goal of this milestone is to ship the first recommendation capability in Orion, to make Joystream apps much more
  - **Content Search V2:** Searching across videos and channels, and also doing search within channels or content categories, is important for effective discovery. Currently, Orion has very rudimentary full text natural language matching on titles and descriptions, but it is very brittle and naive, and often misses the mark. The goal of this milestone is to ship proper modern search capabilities.
  - **Content Infrastructure: Visibility** With greater utilisation and scale, it has become clear that there is a need for better visibility into errors and performance levels at different layers of the infrastructure. This means both capturing data from the consumer and infrastructure layer, and also synthetically probing infrastructure to detect problems as early as possible. Currently, there is quite poor visibility into the performance of infrastructure, and the experience of users in interacting with this infrastructure. The goal of this milestone is to ship a set of integrations and standards for core infrastructure nodes, like Argus, Orion, to facilitate such visibility.
- **Q4**
  - **Creator Tokens:** Creator tokens is a key financial, value capture and community growth primitive unlocked by Joystream. It allows creator to issue a fungible token which captures revenue generated by their channel, and distributes a share of it pro-rate with token holders. There are also complementary features around bootstrapping liquidity, raising funds through a public sale, and also managing access and vesting. This functionality has already been implemented in the blockchain and indexing infrastructure, and very mature designs have already been designed, what remains is to ship a fully working experience which productises this.
  - **Content Infrastructure: Performance:** Having very low latency of content delivery is a critical requirement for any social content product that involves users navigating across lots of different content over time. This depends on having well configured nodes with appropriate technical specifications, and most importantly - properly architecture node software. With the benefit of prior work on visibility we will have a solid foundation for ensuring that we can reach industry benchmarks for video content delivery, and that is the goal of this milestone.
  - **Transcoding & Adaptive Streaming:** Users access content across a wide range of browser, devices, applications and also under heterogeneous and dynamic bandwidth constraints. As it stands, only a single version of each media asset is represented in our metadata standards and backend node software. This means have now way to represent a broad range of encodings and resolutions for media assets, let alone produce all of these. Introducing server-side transcoding in Orion will unlock this, and many other future benefits that come from server-side post-processing (thumbnail extractions, auto-subtitling, etc.). It will also unlock the ability to do adaptive streaming, where a user with a dynamic connection can more quickly see asset resolve and play, and also be able to watch videos under suboptimal circumstances.

## 2024

- **Q1**
  - **Playlists:** A key primitive for organising content is through playlists. We have developed designs and metadata formats for this a long time ago, but in this milestone we will finally ship the ability for publishing and consuming playlists.
  - **Fiat On/Off Ramp:** Getting started with Joystream in one of our consumer apps is super easy, as you are floated a small initial balance of tokens you can only use for transaction fees. However, there are plenty of features which do require more substantial quantities of tokens, such as buying NFTs or Creator Tokens, and conversely, as a creator you are likely eager to not only have the native token, but to cash out to Fiat. For both of these reasons we are working on introducing a proper in-app on/off ramp for consumers and creators of an Atlas app. There are many great ramp partners, such as Transak, which have robust low-friction buy/sell widgets for crypto using credit cards, Apple/Google pay, from across a large number of jurisdictions.
  - **Content Infrastructure: Authentication & Authorisation:** Proper monetisation, both for the DAO and individual creators, depends on being able to practically restrict access to content, or make access conditional. Currently, the infrastructure has no awareness of who the consumer is, or the semantics around what the content is, or any associated authorisation policy. The goal of this milestone is to introduce basic authentication and authorisation at the content layer, enforced by content delivery nodes. This will allow features such as gating videos to only NFT holders for example.
- **Q2**
  - **Video Communities:** Launching a new application for your community using Atlas currently requires a lot of deep technical knowledge. You have to obtain hosting and a domain, start the service, configure it, and then maintain it. This is quite difficult. The goal of this milestone is to create the Reddit to phpBB, in terms of the experience of a prospective community creator and moderator. One requires substantially more work and skill. By instead offering a fully hosted and simple point-and-click feature, we can make it orders of magnitude easier to allow third parties to invite their communities to use Joystream.
  - **Joystream SDK:** Building on top of Joystream today is still a challenging experience. There are no robust libraries or builder documentation for application development. Offering an excellent experience for developer to build apps, and not just use Atlas off-the shelf, will require a significant investment in building out the Joystream SDK. This milestone has as a goal to extract the core of key existing applications, like Atlas and Pioneer, and then to synthesise it all into a new core developer experience, with a suite of excellent tutorials, documentation, examples and also active outreach.
  
# Website Impementation Remark

The key implementation requirement is that the content for the roadmap, and indeed the page, itself should be loaded from a separate content centric document, e.g. JSON encoded, which makes it trivial for non-technical maintainers to open PRs that augment the roadmap. Ideally this roadmap content should be fetched from `master` of some new Github repo, so that it is versioned, public and verifiable. The document should include all versions of the roadmap, not just the most recent one, as required by the revision functionality above.

**Comment by KubaMikolajczyk** [comment]
@bedeho @dmtrjsg the Low-fidelity explorations for the roadmap page is ready to be reviewed ✅ Please let me know your thoughts about this iteration.

🎥 Loom video: https://www.loom.com/share/1e76b3b812a842bbab0509d5f1a305b3?sid=7f1df75c-9768-4e76-b754-a0830fa7feff

📄 Figma file: https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?type=design&node-id=8599-412845&mode=design&t=pf2MQSMjCByf3V7o-4

**Comment by bedeho** [comment]
- Missed these exploration videos, great to see you again as well!
- I love the idea of these icons. Perhaos you can make a small suite of icons that sort of cover generic topics. To me, I can think of things like
  - blockchain
  - data storage
  - data transfer
  - apps
  - wallet
  - coins
  - governance
  - tooling
  - documentation
  - partnership
  - integration
  - nft
  - creator token
- I totally agree on the need to avoid clicking for exploring! 
- **Love** the scrolling effect & tooltips as well.
- Can we add a button or something for sharing the currently selected version?
- Can we also add a share button which allows linking to a specific milestone on a specific version?
- Disclaimer: this will be a legal disclaimer.

**Comment by KubaMikolajczyk** [comment]
@bedeho thank you for the positive feedback 🙇 glad you enjoyed watching my update :)

> Perhaos you can make a small suite of icons that sort of cover generic topics

I will prepare a set of icons for that

> I totally agree on the need to avoid clicking for exploring!

So we can progress with the full roadmap visible at all times :)

> Can we add a button or something for sharing the currently selected version?

Great idea! On it

> Can we also add a share button which allows linking to a specific milestone on a specific version?

Sure thing

**Comment by KubaMikolajczyk** [comment]
@bedeho I have a high fidelity iteration of roadmap page for you to review - tommorow I will be working on user stories to captchure all of that little and big interactions which user will be able to do on the page ✅

🎥 Loom video: https://www.loom.com/share/522b79298b484b9e879d3d7b028173ca?sid=ca6e288b-6d7e-4c3b-9be8-d02444b146ec

📄 Roadmap high fidelity file: https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?type=design&node-id=8646-418771&mode=design&t=Kp4KWZPEK6azSSqD-4

📄 Atlas action icons: https://www.figma.com/file/2tlBY1JQtRMoyjmjJQ9jam/Icons?type=design&node-id=304-2547&mode=design&t=jjlOD8YjznkQCeIZ-4

**Comment by bedeho** [comment]
Looks phenomenal 👍 have a look @DzhideX .

**Comment by DzhideX** [comment]
I usually watch all of these but given the skill of Adam and Kuba there's generally not much to say in terms of any issues 😃  It looks great and all of it seems viable when it comes to the implementation 💯 

I guess there's the navbar thing and I definitely agree that I wouldn't add more items in there. In terms of the solution, I think you might be the best judge of whether you'd like to replace an item or add a dropdown?

**Comment by KubaMikolajczyk** [comment]
@bedeho @DzhideX the work on user stories and remaining elements on roadmap page is finished and ready to be reviewed ✅ its a longer update (39min x1.2) but I believe its worth watching and I have a small surprise there which will help with development of the scroll animation 🤫 🙌

🎥 Loom video: https://www.loom.com/share/0a21ed664b4840e7953c94277ed40fa5?sid=959cafb9-9ef1-4c07-9202-62487d05a66e

📄 Final designs roadmap & single glossary page: https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?type=design&node-id=8646-418771&mode=design&t=aFnywyVyAsxlBZvv-4

📄 User stories roadmap & single glossary page: https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?type=design&node-id=8833-410081&mode=design&t=aFnywyVyAsxlBZvv-4

📄 Markdown styling components: https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?type=design&node-id=8682%3A412679&mode=design&t=aFnywyVyAsxlBZvv-1

🖥️ Scrolling animation shown in video update: https://github.com/Joystream/atlas-resources/blob/main/video-files/Roadmap_scrolling_animation.mp4

**Comment by bedeho** [comment]
- Fantastic review, will make Edvin's job way easier.
- It was on the longer side though, and I don't think my input was needed on most of it, so great if you in the future can point to specific chapters that are needed when the full clip is very long.
- I wonder, do we actually need a sharing button for the full page? can't we just capture the version in the URL, and then when the person copies the URL it's already there?
- The menu solution looks fine, I don't have an opinion about the organization at this time though.
