### ISSUE TITLE
Community page: Add Telegram link

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream-org#652]
# Problem
Although Telegram is not our primary communication tool it is used by new users quite often to ask about the project. The problem is that it isn't on the community page (and can't be verified by users because of this) and currently there are already **three** entirely fake Joystream Telegram channels with 5000+ users each that were created during the lead up to listing.

This is going to be _particularly important_ if we have any future announcements about wrapped tokens, listings or bridges since it seems that these types of announcements end up resulting in particularly increased levels of impersonation attacks.

The link is: https://t.me/JoyStreamOfficial

CC: @bedeho

**Comment by bedeho** [comment]
Yeah, makes sense.
