### ISSUE TITLE
Add Press section to About page

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-org#665]
Add a section "PRESS", but it between "INVESTORS" and "SAFETY & SECURITY", whch features this article 

https://www.coindesk.com/business/2022/03/23/decentralized-creator-platform-joystream-raises-58m/

Lets use the coindesk branding prominently, and a nice preview show of the article itself, and make it clickable easily.

Subtext can be something like "Learn more about us through media stories"

This needs design first, then FE work.

**Comment by KubaMikolajczyk** [comment]
My proposition for press section added to about page is currently ready to be reviewed ✅

🎥 Video update: https://www.loom.com/share/d8d3713ed3d74207a49586d293aadc3b?sid=2b06e080-b614-472c-824f-cb464ac127b4

📄 About final designs: https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?type=design&node-id=8926-165702&mode=design&t=tGF113dpylHbOSU5-4

📄 About user stories: https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?type=design&node-id=8926-165953&mode=design&t=tGF113dpylHbOSU5-4

▶️ About prototype: https://www.figma.com/proto/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?page-id=7380%3A391183&type=design&node-id=8967-92828&viewport=564%2C226%2C0.21&t=PxugvBVFwAZjSu9l-1&scaling=scale-down&starting-point-node-id=8967%3A92828&mode=design

**Comment by bedeho** [comment]
Perfect, nothing more I can say, love it :+1:
