### ISSUE TITLE
Token page: outdated information

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream-org#670]
At bottom of page there are a few sections of text, sort of like a FAQ:
![image](https://github.com/Joystream/joystream-org/assets/50830161/bba8a5b2-3859-480f-91b7-e3ed4b6f66d9)

The following answers are outdated:
* Where do I get JOY tokens? - this links to Pioneer and the link doesn't work, but probably should mention exchange?
* How much is it worth?
* How do I cash out JOY tokens?

**Comment by bedeho** [comment]
Great catch!
