### ISSUE TITLE
Use Tailwind CSS for Frontend

### ISSUE THREAD

**Issue by HeinrichOlfert** [Joystream/joystream-org#679]
Creating the Roadmap section (https://github.com/Joystream/joystream-org/pull/676) spent more than 20 hours because every component has to be created from scratch
Using TailwindCSS, it is a work for 4 ~ 5 hours.

All you need to do is 
`npm install tailwindcss`

**Comment by bedeho** [comment]
Can you explain how exactly tailwindcss makes things faster with a concrete example?

**Comment by HeinrichOlfert** [comment]
Example:
I created this component (src/components/roadmap-page/Quarters/index.js) to use as combobox in the roadmap for selecting specific versions.
It is 354 code lines including CSS.

If I use tailwindcss, I can use this instead.
```
<select id="fruit" name="fruit" class="block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
  <option value="">-- Please choose a fruit --</option>
  <option value="apple">Apple</option>
  <option value="banana">Banana</option>
  <option value="orange">Orange</option>
  <option value="strawberry">Strawberry</option>
</select>
```
10 code lines

**Comment by HeinrichOlfert** [comment]
another example:

I created tooltip component (src/components/Tooltip/index.js) 
47 lines

Tailwind supports tooltips easily
https://flowbite.com/docs/components/tooltips/
