### ISSUE TITLE
Outdated Working Groups image in Pioneer

### ISSUE THREAD

**Issue by jen4ph** [Joystream/joystream-org#736]
Hi again :) 
This photo is outdated I guess, this was taken from testnet. 

<img width="1163" alt="Screenshot 2023-12-12 at 2 54 03 AM" src="https://github.com/Joystream/joystream-org/assets/96877192/31b830f0-c980-46ec-abac-4bfff92c7af6">

**Comment by DzhideX** [comment]
I think the purpose of the image is just to paint the picture of Pioneer and what governance looks like rather than constantly identical and up-to-date with its current state. I think it fulfills the former quite well. Thoughts?

**Comment by bedeho** [comment]
I don't get it? in what sens is it outdated?

But yes, this is just illustrative, not meant to be an up to date view of how Pioneer works in full fidelity at all times.
