### ISSUE TITLE
Issue When Trying to Run the Project Locally

### ISSUE THREAD

**Issue by digitalimplementer** [Joystream/joystream-org#755]
Stylelint's preventing the project from running (errors for the rules "length-zero-no-unit", "declaration-block-trailing-semicolon" and "declaration-block-single-line-max-declarations").

**Comment by DzhideX** [comment]
Hey @digitalimplementer, can you run the following steps and let me know if you still have the same issues:
1. Clone the joystream-org repo
2. Checkout the `development` branch
3. Run `yarn`
4. Run `yarn start`

Also, later when you make a PR make sure it's to the development branch as well.

That should work. If you still have issues let me know!

**Comment by bedeho** [comment]
is this something we need to add to README, or is this just user error on part of @digitalimplementer ?

**Comment by DzhideX** [comment]
Only the last command changed as we had to add an env var for compatibility reasons when updating node versions (so now it's `yarn start` instead of `gatsby develop`). That being said, I think it would be valuable to update the README as a couple more things are out of date now so I'll do it 👍

**Comment by digitalimplementer** [comment]
@DzhideX appreciate your prompt attention to the issue. I'm writing to clarify that the error occurred during project startup using both Gatsby CLI and Yarn. If I am not mistaken, yarn start ultimately executes gatsby develop command. To temporarily circumvent the error, I've disabled specific Stylelint rules within the .stylelintrc configuration file. This allowed me to proceed with local project execution.

**Comment by DzhideX** [comment]
> yarn start ultimately executes gatsby develop command.

Essentially, but `yarn start` also adds a node env var (more specifically: `"develop": "NODE_OPTIONS=--openssl-legacy-provider gatsby develop"`) that adds support for using a newer node engine (v18).

> This allowed me to proceed with local project execution.

Great. If you end up having issues later (e.g. with CI/CD) we can take a better look then 👍
